name: Goldblock
version: '${project.version}'
main: org.by1337gb.goldblock.Goldblock
depend: [PlaceholderAPI, DecentHolograms, Vault]
api-version: 1.13
authors: [ By1337 ]
description: event gold block
commands:
  goldblock:
    description: Standart Command
    aliases: [gb]
    usage: Usage /goldblock [tp/reload]
permissions:
  gb.*:
    description: All cmd
    default: op
    children:
      fgb.tp: true
      fgb.reload: true
  gb.tp:
    description: /gb tp
    default: op
  gb.reload:
    description: /gb reload
    default: op
  gb.start:
    description: /gb start
    default: op